### ISSUE TITLE
Animationen Haeuser/Terrain

### ISSUE THREAD

**Issue by siredmar** [roybaer/mdcii-engine#13]
Hi!
Nachdem ich mich nun etwas mit den Animationen von Gebaeuden und Terrain beschaeftigt habe, aber noch immer nicht 100%ig sagen kann, dass ich es verstanden habe, oeffne ich hier nochmal eine Diskussionsrunde.

Was ich weiss:
In den meisten Faellen ist Rotate = Size.hoehe * Size.breite. Es gibt hier ein paar Ausnahmen. Dabei ist die Size immer 1x1 und Rotate = 0. Damit sollte man umgehen koennen.
Rotate ist also die Anzahl an Grafiken bzw. Tiles, die gemalt werden soll fuer ein Objekt (egal, ob  Gebaeude oder Terrain).

# Beispiel1 - Schloss:
```
Gfx: 4964
Size: 5x7
Rotate: 35
AnimTime: "TimeNever"
AnimAdd: 0
AnimAnz: ungesetzt
```
Da die Animation offenbar deaktiviert ist (AnimAnz = ungesetzt), gibt es fuer das Schloss logierweise keine Anmation. Es muss also fuer alle vier Ansichten jeweils 35 Bilder geben. Der Grafikindex innerhalb der stadtfld.bsh muss also von der Drehrichtung des Gebaeudes, der Drehrichtung der Kamera und der jeweiligen Groesse des Objekts (Rotate oder Size.breite * Size.hoehe) ergeben.

Ich hab mir mit dem mdcii-bshdump mal die Grafiken exportiert um zu verstehen, wie das Indexing funktioniert. Am Beispiel vom Schloss erhalte ich vom Startindex aus der haeuser.cod 4964 den rechten unteren Punkt des Schlosses gefolgt, von 4 transparenten Bildern, um nicht das bereits gemalte zu ueberpineln. 
Hier ein Beispiel, wie die Indizes fuer das Schloss liegen koennten bzw. welches Muster ich sehe und erwarte. Ich beschraenke mich jetzt erstmal nur auf eine Ansicht.
Wenn ich mir die ersten Indizes der Grafiken anschaue, erwarte ich so etwas
```
                  
                       --- \                  
                   ---/  a  \                 
               ---/   b   l  \                
           ---/   c    l   l  \               
       ---/   d    l    l   l  \              
   ---/   e    l    l    l    1 -             
--/   f    l    l    l    2  ---              
\ g    l    l    l    3  ---/                 
 \ l    l    l    4  ---/                     
  \ l    l    5  ---/                         
   \ l    6  ---/                             
    \ 7  ---/                                 
     ---/                                        
```

a ist der vordere rechte Startpunkt: Index 4964 -> Grafik leer
### Erste Reihe: hoehe, breite[0]
a und l: leere Grafiken 4964, 4965, 4966, 4967
1 tatsaechliche Grafik: Index: 4968
### Zweite Reihe: hoehe, breite[1]
b und l: leere Grafiken 4969, 4970, 4971, 4972
2 tatsaechliche Grafik: Index: 4973
### Dritte Reihe: hoehe, breite[2]
b und l: leere Grafiken 4974, 4975, 4976, 4977
2 tatsaechliche Grafik: Index: 4978
### Vierte Reihe: hoehe, breite[3]
b und l: leere Grafiken 4979, 4980, 4981, 4982
2 tatsaechliche Grafik: Index: 4983
### Fuenfte Reihe: hoehe, breite[4]
b und l: leere Grafiken 4984, 4985, 4986, 4987
2 tatsaechliche Grafik: Index: 4988
### Sechste Reihe: hoehe, breite[5]
b und l: leere Grafiken 4989, 4990, 4991, 4992
2 tatsaechliche Grafik: Index: 4993
### Siebte Reihe: hoehe, breite[6]
b und l: leere Grafiken 4994, 4995, 4996, 4997
2 tatsaechliche Grafik: Index: 4998

Ergibt genau 35 Bilder == Rotate == Size.breite * Size.hoehe

Was ich aber tatsaechlich sehe ist, dass die ersten Reihen der Breite noch "korrekt" erscheinen.

### Erste Reihe: hoehe, breite[0]
a und l: leere Grafiken 4964, 4965, 4966, 4967
1 tatsaechliche Grafik: Index: 4968
### Zweite Reihe: hoehe, breite[1]
b und l: leere Grafiken 4969, 4970, 4971, 4972
2 tatsaechliche Grafik: Index: 4973
### Dritte Reihe: hoehe, breite[2]
b und l: leere Grafiken 4974, 4975, 4976, 4977
2 tatsaechliche Grafik: Index: 4978
### Vierte Reihe: hoehe, breite[3]
b und l: leere Grafiken 4979, 4980, 4981, 4982
2 tatsaechliche Grafik: Index: 4983
### Fuenfte Reihe: hoehe, breite[4]
b und l: leere Grafiken 4984, 4985, 4986, 4987
2 tatsaechliche Grafik: Index: 4988
### Sechste Reihe: hoehe, breite[5]
b und l: leere Grafiken 4989, 4990, 4991, 4992
2 tatsaechliche Grafik: Index: 4993

Fuer die Siebte Reihe jedoch geht das System kaputt. 
Ich koennte aber nur Vermutungen anstellen warum. Und nicht mal da faellt mir was dazu ein.
### Siebte Reihe: hoehe, breite[6]
Die naechsten Schlossteile sind optisch anhand der Bilder abgeglichen, auf der rechten Haelfte vom Bild abgesehen von 4998, da ist es ueber beide haelften geteilt.
4998, 4997, 4996, 4995. 4994

Ich versteh das nicht. Kann mir da jemand auf die Spruenge helfen?

# Beispiel 2 - Windmuehle:
```
Gfx: 1816
Size: 2x2
Rotate: 4
AnimTime: 90
AnimAdd: 16
AnimAnz: 1
```
Wieder: Beschraenkung auf nur eine Ansicht.
AnimAnz: Wir haben neben dem Grundbild noch 1 weiteres -> 2 Animationsschritte
Rotate: Es gibt pro vollstaendigem Gebaeudebild 4 Grafiken. 
### Animatinsschritt 1:
1: 1816: leer
2: 1817
3: 1818
4: 1819
### Animationsschritt 2 (Indexes + 16)
1: 1832: (leer)
2: 1833
3: 1834
4: 1835

```
    --- \                  
---/  1  \                 
\  3    2  \                
 \  4  ---/                 
  ---/
```
Bei der Muehle scheint das oben beschriebene System von der Berechnung der Indizes Sinn zu machen. Da funktioniert es.

Kann mir jemand erklaeren, was da los ist?

**Comment by roybaer** [comment]
Hilft `doc/grafikreihenfolge.md` weiter?
Die nicht-transparenten Grafiken sind im Grunde nur das vordere „V“.
Alles was da drüber (also dahinter) ist, wird mit den transparenten Platzhaltern gefüllt, die übrigens im BSH-Archiv dedupliziert sind.

Und ja, „Rotate: 0“ scheint in der Tat zu bedeuten, dass es nur genau eine Ansicht gibt.

**Comment by siredmar** [comment]
Die doc hilft nur weiter, um zu verifizieren, dass ich z.B. die Muehle verstanden habe. Was sich mit dem Schloss aber tut, verstehe ich damit immernoch nicht.
Was meinst du mit 'vordere "V"'?

**Comment by roybaer** [comment]
Ich meine dieses „V“ aus „g“s:

```
      l
    l   l
  l   l   l
g   l   l   g
  g   l   g
    g   g
      g
```
Dabei steht „l“ für die leeren Felder und „g“ für die tatsächlichen Grafiken.

**Comment by siredmar** [comment]
Jetzt verstehe ich. Danke!
