### ISSUE TITLE
Platzierung der Tiles abhaengig von der Drehung

### ISSUE THREAD

**Issue by siredmar** [roybaer/mdcii-engine#14]
Eine paar Fragen zum Datenformat der Inseln. In der haeuser.cod werden die Objekte jeweils mit einer GFX-Id adressiert und ueber diverse Parameter die Sub-GFX-Ids berechnet. Anhand der Groesse und Animationsmenge bekommt man hier entsprechend eine Vielzahl an Tripletts (x, y, Gfx). 

## Startkoordinaten fuer Haeuser

Ist die Interne Darstellung der Insel so, dass auch nur das Starteck eines Hauses gespeichert wird? Durch die Berechneten Sub-Gfx-Ids und die Rotation ist ja dann berechenbar, welche Tiles mit Absoluten Koordinaten und welchen Sub-Gfx gemalt werden soll.

Also in einem Bild nochmal:
Gras: `9`
Starteck eines Hauses (2x2): `s`
Nix: `.`

Drehung 0:
```
  0123456789 - x
0 9999999999
1 999s.99999
2 999..99999
3 9999999999
|
y
```

**A**: Ist das so korrekt?

## Gedrehte Objekte

Unter der Annahme, dass die Frage zuvor mit Ja beantwortet wird, noch eine weitere Frage.
Die Kamera malt ja einen sichtbaren Ausschnitt der ggf. sichtbaren Insel. Ich beziehe mich im Folgenden auf die grafikreihenfolgen.md in docs. Ich bitte hier um Bestaetigung meiner Annahme.
Wird die Kamera gedreht, veraendert sich dabei die Interne Darstellung, dass quasi die jewils korrekten Grafiken fuer die Drehung und den Animationsschritt angezeigt werden. So weit klar. 
Egal bei welcher Drehung werden dabei exakt dieselben absoluten Koordinatenpunkte auf der Weltkarte gemalt, nur eben mit anderen Grafiken. D.h. ich muss nicht aktiv in die X-Y Koordinaten eingreifen, weil sich die Startkante (markiert mit s im Bild) verschoben hat. z.B. so

`Drehung 0`          ` Drehung 1 `          ` Drehung 2`          `  Drehung 3 `
`9999999999    9999999999    9999999999    9999999999` 
`999s.99999    999.s99999    999..99999    999..99999`   
`999..99999     999..99999    999.s99999    999s.99999`  
`9999999999    9999999999    9999999999    9999999999` 

**B**: Ist das so korrekt?

## Objekte mit nicht quadratischer Grundflaeche
Eine andere Variante wie bei der Frage davor ist diese hier. Diese wird erst richtig interessant, wenn man nicht quadratische Objekte hat (z.B. Triumpfbogen 1x3 oder Schloss 5x7)

Ist es in wirklichkeit so intern verwaltet?

`Drehung 0`          ` Drehung 1 `          ` Drehung 2`          `  Drehung 3 `
`9999999999    9999999999    9999999999    999.999999` 
`9999999999    9999999999    9999999999    999.999999` 
`999s..9999    999s999999    99..s99999    999s999999`   
`9999999999     999.999999    9999999999    9999999999`  
`9999999999    999.999999    9999999999    9999999999` 

Das haette die Implikation, dass ich abhaengig von der Drehung die korrekte Grafik berechne UND diese an die korrekt berechnete absolute Koordinate auf der Welt bzw. der Insel plaziere.

**C**: Ist das so korrekt?

**Comment by roybaer** [comment]
Ja. Das ist so alles korrekt.

Die Grafikindizes werden aus den internen zweidimensionalen Arrays für die Inseln von der Funktion `grafik_bebauung_inselfeld` in der jeweils benötigten Fassung berechnet. Man muss sich um die Ausrichtung also nur noch kümmern, wenn man in ebendiesen Prozess eingreift.

**Comment by siredmar** [comment]
Ok, gut. 
Ich befinde mich dabei Objekte zu erzeugen, dessen Animationsdaten bequem automatisch berechnet werden. 
Hintergrund ist der, dass spaeter Objekte ja auch anklickbar sein sollen, eine Zuweisung per Spieler, Produktion, Lagerstaende etc.
Ein Objekt kann man in meinem aktuellen Branch anlegen mit der jeweiligen ID mit Koordinaten, und wem der Spieler gehoert. Ich habe nur gerade noch Probleme die korrekten Koordinaten auszurechnen fuer die einzelnen Tiles der Gebaeude. Aber das krieg ich auch noch hin. 
Dann sollen die Inseln jeweils Vektoren aus Objekten haben, die einzeln animiert und gesteuert werden koennen.

**Comment by roybaer** [comment]
Moment, Moment...

Wäre das nicht monströs ineffizient?
1) Das Objekt unter der Maus wird ja jetzt schon erfasst und die Koordinaten zurückgegeben
2) Der Gebäudetyp und der Besitzer sind in den Inseldaten für jedes Feld schon gespeichert
3) Die Lagerstände o.ä. sind in dem jeweils passenden Vektor (PRODLIST, SIEDLER usw.) auch schon drin
4) Ein Animationsattribut ist in den Inselfeldern auch mit drin. Genau das wird ja in meiner Version benutzt. Da wird einmal die PRODLIST durchgerattert und an den jeweiligen Koordinaten das Animationsattribut in den Inseldaten angepasst.

Man sollte im Auge behalten, dass das Original inklusive Betriebssystem mit 16 MB RAM lief. Das muss ja bei dem Nachbau nicht völlig aus dem Ruder laufen.

Für die Programmstruktur können wir ja gerne Objekte zur Abstraktion nehmen, ich würde da aber vorschlagen, inline-Funktionen zu nehmen, die bloß das obenstehende kapseln und ansonsten nur das nötigste selbst speichern.

Nachtrag:
Was verursacht eigentlich gerade die ganzen Probleme? Der Grafikteil funktioniert doch schon beinahe einwandfrei. Schreibst du gerade alles neu?

**Comment by siredmar** [comment]
> Wäre das nicht monströs ineffizient?

Noe, die Berechnungen finden alle im Vorfeld statt und werden per Dependency Injection den Objekten zur Verfuegung gestellt. Am Ende ist es eine Funktion und weitergereichte Pointer auf die tatsaechlichen Daten.

>Man sollte im Auge behalten, dass das Original inklusive Betriebssystem mit 16 MB RAM lief. Das muss ja bei dem Nachbau nicht völlig aus dem Ruder laufen.

Deswegen darf man allerdings trotzdem Code schreiben, der sich zumindest leichter warten laesst. Ich schreibe meinen Code in der Regel so, dass ich ihn (hoffentlich) noch in einem Jahr verstehe und verzichte dabei mit Absicht auf Konstrukte, die vielleicht Platzsparend und womoeglich etwas effizienter sind, dafuer allerdings so kryptisch sind, dass ich sie bald selbst nicht mehr verstehen wuerde. Ich fange erst dann an zu optimieren, wenn ich ein Problem feststelle.

> Das Objekt unter der Maus wird ja jetzt schon erfasst und die Koordinaten zurückgegeben
Der Gebäudetyp und der Besitzer sind in den Inseldaten für jedes Feld schon gespeichert
Die Lagerstände o.ä. sind in dem jeweils passenden Vektor (PRODLIST, SIEDLER usw.) auch schon drin
Ein Animationsattribut ist in den Inselfeldern auch mit drin. Genau das wird ja in meiner Version benutzt. Da wird einmal die PRODLIST durchgerattert und an den jeweiligen Koordinaten das Animationsattribut in den Inseldaten angepasst.

Versteh mich bitte nicht falsch! Du hast da was richtig krasses geschaffen und ich kann nur meinen Hut davor ziehen. Mir fehlt aber an manchen Stellen einfach eine Kapselung diverser Dinge, Testbarkeit, etc. Der Code scheint wirklich auf Performance optimiert zu sein. Ich vermute aber, dass man hierbei wahrscheinlich ueberhaupt kein Problem haben wird - selbst nicht auf einem Raspberry Pi. 

> Was verursacht eigentlich gerade die ganzen Probleme? Der Grafikteil funktioniert doch schon beinahe einwandfrei. Schreibst du gerade alles neu?

Es sieht irgendwie fast danach aus, ja. Warum? Weil ich den bisherigen Code einfach nicht raffe, bzw. ich noch so weit davon entfernt war zu versehen was du genau da eigenlich tust. Das Problem ist, dass irgendwie die halbe Logik und Berechnung nicht auf die Daten matcht, die man aus der haeuser.cod gewinnen kann. 
Oder wie gesagt: Ich war noch zu weit davon entfernt es korrekt einzubinden.
Ich hatte allerdings vor an einem gewissen Punkt wieder an deinen Code anzupropfen. Das waere genau die `grafik_bebauung_inselfeld` gewesen.

**Comment by siredmar** [comment]
Hi!
Ich habe nach einer laengeren Pause mal wieder etwas Zeit gefunden und es endlich hinbeommen die Daten der haeuser.cod fuer die Renderingroutinen in der insel.cpp zu benutzen.
Es ist ziemlich viel Kram passiert in meinen Branches. Ich versuche jetzt mal einen sauberen Stand vom aktuellen Master zu erzeugen, dass man da einen sauberen Merge hinbekommt. 
Grunsaetzlich kann man jetzt mit dem COD Parser die bebauung.txt und grafiken.txt loswerden.
